### ISSUE TITLE
Compatibility with postcss-functions

### ISSUE THREAD

**Issue by CKGrafico** [Scrum/postcss-at-rules-variables#208]
Is it possible to make this plugin compatible with `postcss-functions` ? Is there any alternative?

I have code like:
```
 @each $value, $i in values($map) {
```

where values is a function

**Comment by Scrum** [comment]
you tried use custom variables in function like as ?
```postcss
@each $value, $i in values(var(--map)) {
```

**Comment by CKGrafico** [comment]
Yes, not working too because functions bust be evaluated before each :(

**Comment by Scrum** [comment]
put the plugin `postcss-at-rules-variables` above the plugin `postcss-function` in the plugins list `postcss`

**Comment by CKGrafico** [comment]
Yes that was the first approach but nothing, I've solved my issue ussing replace plugin but not the ebst scenario xD
